# Generated by Django 4.0.6 on 2022-07-12 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=255)),
                ('gender', models.CharField(max_length=30, verbose_name='gender')),
                ('date_of_birth', models.DateField(default=datetime.datetime.now)),
                ('industry', models.CharField(max_length=20)),
                ('salary', models.FloatField(blank=True, default=0.0, null=True, verbose_name='salary')),
                ('years_of_experience', models.IntegerField(blank=True, default=0, verbose_name='years_of_experience')),
            ],
        ),
    ]
