# Generated by Django 4.0.6 on 2022-07-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='years_of_experience'),
        ),
    ]
