# Generated by Django 4.0.6 on 2022-07-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_employee_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='industry',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
